<table class="tbl-cart">
    <thead>
        <tr>
            <th>product name</th>
            <th>product code</th>
            <th>unit price</th>
            <th>quantity</th>
            <th>subtotal</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>
<hr>
<table class="tbl-total">
    <tfoot>
        <tr>
            <td>total:</td>
            <td>$440.50</td>
        </tr>
    </tfoot>
    <tbody>
        <tr>
            <td>subtotal:</td>
            <td>$434.50</td>
        </tr>
        <tr>
            <td>shipping:</td>
            <td>$6.00</td>
        </tr>
        <tr>
            <td>tax (0%):</td>
            <td>$0.00</td>
        </tr>
    </tbody>
</table>            
<hr>
<table class="tbl-striped">                      
    <tbody>
        <tr>
            <td>product name</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>price</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>brand</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>availability</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>rating</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>summary</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>weight</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td>demensions</td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
    </tbody>
</table>